eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka,http://127.0.0.1:10087/eureka
  instance:
    prefer-ip-address: true
server:
  port: 10010
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
#     默认过滤器，对所有路由都有效
      default-filters:
        # 添加响应头
        - AddResponseHeader=X-Response-Default-MyName, zy
#     跨域
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: *  # *表示全部
#           allowedOrigins:
#             - "http://xx.xx"
            allowedMethods:
              - GET
#     路由
      routes:
#        路由id，自定义
        - id: user-service-route
#         代理的服务地址;lb表示从eureka中获取具体服务(自动负载均衡)
          uri: lb://user-service # http://127.0.0.1:9091
#         断言：配置映射地址（将路径符合Path规则的请求，代理到uri中去）
          predicates:
            - Path=/**
#          过滤
          filters:
#              添加前缀(访问的url 加上这个前缀，再去匹配path)
            - PrefixPath=/users
#              去掉一个前缀（等于几 就去掉几个）（访问的url 去掉这个前缀，再去匹配path）
#            - StripPrefix=1
#              自定义过滤器
#            - MyParam=name



#熔断参数配置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000
# 负载均衡参数配置
ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 2000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0
